### ISSUE TITLE
Problem on mIoU, IoU metrics ?

### ISSUE THREAD

**Issue by luigui2906** [charlesCXK/TorchSSC#7]
Hi,

I was using and testing the code and I think there might be an issue in the way mIoU and IoU are calculated. Referring to the mask you use for mIoU calculation : 

https://github.com/charlesCXK/TorchSSC/blob/12e76a0cddf258336e1a194ea1af3210466bcf2c/model/sketch.nyu/eval.py#L99

if I understand correctly, you are ignoring all voxels that are seen in the camera frustum and considering only occluded voxels (label_weights>0). In my opinion, evaluation should be performed in all voxels in the scene that have valid semantic labels (`flat_label != 255`), considering that you have also a class that predicts free voxels (`flat_pred == 0`).

Similarly for the IoU, you should do the same evaluation but now grouping all predicted semantic classes ( `flat_pred > 0` ) as a single class (occupied). Again, the mask should only be (`flat_label != 255`). 

However, for semantic completion (IoU) you are considering occluded (`label_weight > 0`), valid (`flat_label  != 255`) and that have not mapped features from the 2D image to 3D grid (`mapping == 307200`) for the calculation:

https://github.com/charlesCXK/TorchSSC/blob/12e76a0cddf258336e1a194ea1af3210466bcf2c/model/sketch.nyu/eval.py#L108

Could you please clarify this ? 

Thanks again for the work and for sharing the code.

**Comment by charlesCXK** [comment]
Hi,
It is a good question. I want to point out that `label_weight` != `label`
In fact, `label_weight == 1` means such areas in my code: all the occluded regions (except 255) and the observed surface. I save such areas into a single file so that I could easily obtain them during training and evaluation. In other words, voxels that have a label of 255, and the observed free voxels (which represent atmosphere) are ignored.

I follow SSCNet to evaluate the performance. They define SSC mIoU as mIoU on the **observed surface and the occluded region except 255** (label_weight == 1 in my code), and SC IoU as the **binary IoU on the occluded region only**. Here 'binary' means all voxels who are assigned with a label > 0 during the evaluation will be viewed as 'occupied', and label 0 is viewed as 'empty'. This metric is easy to understand because the observed region does not need to complete. 

I copied some sentences from their paper, please refer to their paper for more details~

**_For the semantic scene completion task, we evaluate the IoU of each object classes on both the observed and occluded voxels. For the scene completion task, we treat all non-empty object class as one category and evaluate IoU of the binary predictions on occluded voxels. Following Firman et al. [3], we do not evaluate on voxels outside the view or the room._**

**Comment by luigui2906** [comment]
Thanks for clarifying,

As you state for SSC task _**"For the semantic scene completion task, we evaluate the IoU of each object classes on both the observed and occluded voxels"**_, so this would mean all observed voxels **(including free ones before observed surface)** and not only those on the observed surface, am I wrong ? 

I was checking the code from SSCNet and they seem to calculate mIoU on both the observed and occluded voxels as you say, but only close to the surface though `( abs(ftsdf_values)<1 | ftsdf_values==-1 )`. 

https://github.com/shurans/sscnet/blob/61b4060b435fa93798ea1ced2b87c55bee2433bc/matlab_code/evaluation_script.m#L67

For IoU in the other hand, they seem to evaluate only in occluded voxels but including also observed surface `(ftsdf_values<0 & ftsdf_values>=-1)`. I guess fTSDF values equal to -1 should correspond to the surface. 

https://github.com/shurans/sscnet/blob/61b4060b435fa93798ea1ced2b87c55bee2433bc/matlab_code/evaluate_completion.m#L2

I think this is confusing and I wonder if all metrics have been calculated in the same way for the different approaches.

**Comment by charlesCXK** [comment]
Hi,
For the first question, the observed shouldn't be involved. These areas could be computed from the depth map and the camera parameters, and we could simply assign label '0' to them because we know they are atmosphere voxels.

For the second question, the observed surface has TSDF value == 0. Then the corresponding fTSDF value should be 1. You could also refer to Figure 5 (d) in SSCNet's paper for better understanding, where the region marked with red means fTSDF == 1.

**Comment by luigui2906** [comment]
I see,

So basically for the mIoU you measure what it is unknown classwise, which corresponds to classes on the observed surface and occluded voxels. Atmosphere is already known (free).

For the IoU since observed surface is already known in terms of occupancy, the metric measures occluded space only.

Thanks for clarifying and for the great response.
